### ISSUE TITLE
cy.task(confirmMetamaskTransaction) failed with new version 3.0.3

### ISSUE THREAD

**Issue by Vishwas-02** [Synthetixio/synpress#587] opened 2022-11-21 08:06 UTC
While working the new version 3.0.3 , my basic command of transaction is getting failed .  Can you guys please provide us firm solution . 

This command is not accessing Metamask windows .

![image](https://user-images.githubusercontent.com/101315014/202996430-2e28e529-e10d-4c85-9b44-2b0d20e59576.png)

**Comment by bmarinescu** [comment] 2022-11-21 12:49
Getting the same thing, upon further inspection we found that the metamask signature window does not show up anymore when calling window.ethereum.request({method: 'eth_requestAccounts'}) since updating to 3.0.4. 2.4.1-beta.2 does not have this issue.

**Comment by drptbl** [comment] 2022-11-21 21:51
@Vishwas-02 @bmarinescu Hey guys, do you have any reproduction steps or example code, so that I can reproduce this issue on my local machine?

Please keep in mind that:
- synpress@2 runs on metamask@9 (pre-eip-1559)
- synpress@3 runs on metamask@10 (post-eip-1559)

Thanks,
Jakub.

**Comment by emmabubu** [comment] 2022-11-25 05:18
I have encountered the same issue when using Synpress 3.0.4, metamask confirm transaction window does not show up, and gives such error code:
<img width="1300" alt="Screen Shot 2022-11-25 at 13 15 35" src="https://user-images.githubusercontent.com/100118606/203906218-7cc21542-62b3-418c-bc3f-c5963553356f.png">

**Comment by drptbl** [comment] 2022-11-26 01:26
@emmabubu this is correct way to do it:
```
    cy.visit('/#/swap');
    cy.contains('button', 'Connect Wallet').click();
    cy.contains('button', 'MetaMask').click();
    cy.acceptMetamaskAccess();
    cy.get('div#swap-currency-input input').type('0.01');
    cy.get('div#swap-currency-output .open-currency-select-button').click();
    cy.contains('Uniswap').click();
    cy.contains('button', 'Swap').click();
    cy.contains('button', 'Confirm Swap', { timeout: 7000 }).click();
    cy.confirmMetamaskTransaction();
```

Nevertheless I'm still not able to reproduce issue from @Vishwas-02 and @bmarinescu as no example repository/code has been provided in this issue.

**Comment by tomeq93** [comment] 2022-11-26 08:54
Hey @drptbl all I do is 
`    cy.confirmMetamaskTransaction();
`
It hangs on 
```
log('[confirmTransaction] Getting origin value..');
txData.origin = await playwright.waitAndGetValue(
        confirmPageElements.originValue,
        notificationPage,
      );
```
and fails to find `'.notification .confirm-page-container-content .tabs .confirm-page-container-content__data .confirm-page-container-content__data-box:nth-child(1) .confirm-page-container-content__data-field:nth-child(1) div:nth-child(2)'`
if I comment out getting origin, bytes and hexData all is working fine

**Comment by drptbl** [comment] 2022-11-26 19:28
@tomeq93 thanks for reporting 🙏. I will fix it until end of this weekend.

**Comment by drptbl** [comment] 2022-11-26 22:19
@tomeq93 @emmabubu @Vishwas-02 @bmarinescu  
This should be fixed in `@synthetixio/synpress@3.0.5`. Sorry for issues!

**Comment by emmabubu** [comment] 2022-11-27 05:54
> @emmabubu this is correct way to do it:
> 
> ```
>     cy.visit('/#/swap');
>     cy.contains('button', 'Connect Wallet').click();
>     cy.contains('button', 'MetaMask').click();
>     cy.acceptMetamaskAccess();
>     cy.get('div#swap-currency-input input').type('0.01');
>     cy.get('div#swap-currency-output .open-currency-select-button').click();
>     cy.contains('Uniswap').click();
>     cy.contains('button', 'Swap').click();
>     cy.contains('button', 'Confirm Swap', { timeout: 7000 }).click();
>     cy.confirmMetamaskTransaction();
> ```
> 
> Nevertheless I'm still not able to reproduce issue from @Vishwas-02 and @bmarinescu as no example repository/code has been provided in this issue.

@drptbl `cy.confirmMetamaskTransaction()` works after using your code, thank you so much!

**Comment by tomeq93** [comment] 2022-11-27 09:23
@drptbl yep, confirmation looks good now, thank you ❤️

**Comment by drptbl** [comment] 2022-11-27 10:56
Thank you @tomeq93 @emmabubu 🙏

**Closed** 2022-11-27 10:56 UTC
